import Navbar from '@/components/Home/Navbar';
import '@/app/globals.css';

export const metadata = {
    title: 'SHRK | Communicate, Collaborate, Create',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
