import Navbar from '@/components/Home/Navbar';
import '@/app/globals.css';
import { SessionProvider } from 'next-auth/react';

export const metadata = {
    title: 'SHRK | Communicate, Collaborate, Create',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <SessionProvider>
                    <Navbar />
                    {children}
                </SessionProvider>
            </body>
        </html>
    );
}
