import '@/app/globals.css';
import Navbar from '@/components/Pricing/Navbar';
import { SessionProvider } from 'next-auth/react';

export const metadata = {
    title: 'SHRK | Communicate, Collaborate, Create',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
